# Generated by Django 4.0.4 on 2022-04-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOSS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafield',
            old_name='ph_no',
            new_name='user_id',
        ),
    ]
